### ISSUE TITLE
The new /reloadredis command does not seem to stop tasks correctly

### ISSUE THREAD

**Issue by Govindass** [Limework/RediSkript#1]
I find it still doing connections to the wrong IP address after reloading, while at the same time being connected to the right IP address, must find why, looks like a memory leak.

this behavior can be noticed when using NetworkInterceptor plugin

**Comment by ham1255** [comment]
Lol I found the problem it's in main class you keep remaking new redis manager as I said redis manager is reusable don't make new one

**Comment by ham1255** [comment]
I will take care of it in 2 weeks  or possibly less since I have stuff to do.

**Comment by Govindass** [comment]
> 
> 
> Lol I found the problem it's in main class you keep remaking new redis manager as I said redis manager is reusable don't make new one

I think the problem is in Jedis doing some kind of ping-ponging to that IP, because redis manager in itself doesn't do any IP-based connections, thus it is not a problem of recreating redis manager, unless jedis somehow keeps connecting to wrong IP due to it?

**Comment by Govindass** [comment]
Fixed in next version
