### ISSUE TITLE
Problem with connection on Windows

### ISSUE THREAD

**Issue by wallxq** [Limework/RediSkript#10]
Hi i install REDIS from https://github.com/dmajkic/redis/downloads (lastest) for windows and i have problem. On start REDIS and first start server with RediSkript i have this:
`[12:24:27 INFO]: [RediSkript] Connecting to redis...
[12:24:27 WARN]: [RediSkript] Connection to redis has failed! Reconnecting...`
Than i close server and go to config RediSkript. I change useTLS to true and start again server. Server stuck on:
`[12:26:26 INFO]: [RediSkript] Enabling RediSkript v1.3.1`
and REDIS change to:
`[4140] 18 Dec 12:26:47 - 1 clients connected (0 slaves), 1188800 bytes in use` from 0 clients.
I wait minute and:
`[4140] 18 Dec 12:27:22 - 2 clients connected (0 slaves), 1197704 bytes in use` change to 2 but RediSkript don't allow start server and stuck. I am waiting 3 minutes and i have this again but server start:
`[12:29:30 INFO]: [RediSkript] Connecting to redis...
[12:29:30 WARN]: [RediSkript] Connection to redis has failed! Reconnecting...`
and in REDIS:
`[4140] 18 Dec 12:29:26 - Client closed connection
[4140] 18 Dec 12:29:29 - 1 clients connected (0 slaves), 1188800 bytes in use`
30 seconds later:
`[4140] 18 Dec 12:30:24 - 0 clients connected (0 slaves), 1179896 bytes in use`
and this repeat from 0 to 1.
Than i give command /reloadredis in server.
`[12:31:39 INFO]: [RediSkript] Connecting to redis...
[12:31:39 WARN]: [RediSkript] Connection to redis has failed! Reconnecting...` this stop and REDIS give this:
`[4140] 18 Dec 12:30:24 - 0 clients connected (0 slaves), 1179896 bytes in use
[4140] 18 Dec 12:30:26 - Accepted 127.0.0.1:50627
[4140] 18 Dec 12:30:29 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:34 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:39 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:44 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:49 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:54 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:30:59 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:04 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:09 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:14 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:19 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:24 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:29 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:34 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:39 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:44 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:49 - 1 clients connected (0 slaves), 1188800 bytes in use
[4140] 18 Dec 12:31:50 - Accepted 127.0.0.1:50670
[4140] 18 Dec 12:31:54 - 2 clients connected (0 slaves), 1197704 bytes in use`
But its only for few minutes and plugin can't save variables.

**Comment by ham1255** [comment]
could you post your server log?

**Comment by ham1255** [comment]
and i almost forgot the config of the plugin and and redis config aswell

**Comment by wallxq** [comment]
Logs: https://pastebin.com/C43LEf9T
Redis conf: https://pastebin.com/CBpsnwCq
RediSkript conf: https://pastebin.com/yWjmrn1v

**Comment by Govindass** [comment]
as I see you're using an older version of Redis, only 6.0.6+ supports TLS properly, set TLS to false

**Comment by ham1255** [comment]
and try disable EncryptMessages

**Comment by wallxq** [comment]
I do it, disbale EncryptMessages and TLS and i do it on clear server with only skript and RediSkript.
![clear](https://user-images.githubusercontent.com/36922415/102611148-ac4d9a00-412e-11eb-8032-21cfa245a717.PNG)

**Comment by Govindass** [comment]
your password in the config seems to be the same as default - I think it is likely failing to connect due to wrong password

**Comment by wallxq** [comment]
Without TLS, it doesn't want to connect for a while. It just makes a connection and breaks it off at the same time.

**Comment by Govindass** [comment]
> 
> 
> Without TLS, it doesn't want to connect for a while. It just makes a connection and breaks it off at the same time.

could you post your log from this situation? that shouldn't be happening

**Comment by wallxq** [comment]
https://pastebin.com/JNhqX2uz
and where i can change password of redis in config file? i can't saw line of password 0.o

**Comment by Govindass** [comment]
> 
> 
> https://pastebin.com/JNhqX2uz
> and where i can change password of redis in config file? i can't saw line of password 0.o

we only work with Redis 6, so I don't know, but in Redis 6 there's an entry called "requirepass"

**Comment by wallxq** [comment]
I find `# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#
# requirepass foobared`
than i must change to:
`# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#
requirepass testpassword`
?

**Comment by Govindass** [comment]
> 
> 
> I find ` Warning: since Redis is pretty fast an outside user can try up to
> 150k passwords per second against a good box. This means that you should
> use a very strong password otherwise it will be very easy to break.
> 
> requirepass foobared`than i must change to:` Warning: since Redis is pretty fast an outside user can try up to
> 150k passwords per second against a good box. This means that you should
> use a very strong password otherwise it will be very easy to break.
> 
> requirepass testpassword`
> ?

yes, that should work

**Comment by ham1255** [comment]
he is using redis 2 i think for windows since that redis version was last release for windows?

**Comment by wallxq** [comment]
After changing the password in REDIS and RediSkript, the problem remains unchanged. As for the REDIS version, at least I haven't found a newer one for Windows.

**Comment by Govindass** [comment]
I will setup redis on windows and see if it's a problem in redis version

**Comment by wallxq** [comment]
Okay, I'm waiting :)

**Comment by Govindass** [comment]
> 
> 
> Okay, I'm waiting :)

it works, you just need to run it from command line with redis config directory specified

in my case:
```
C:\Users\Govindas\Desktop\redis\redis-server.exe C:\Users\Govindas\Desktop\redis\redis.conf
```

**Comment by wallxq** [comment]
Than run CMD as admin and paste directory of REDIS?
![tak](https://user-images.githubusercontent.com/36922415/102613684-38fa5700-4133-11eb-9d79-4deae60fc43f.PNG)

**Comment by Govindass** [comment]
> 
> 
> Than run CMD as admin and paste directory of REDIS?
> ![tak](https://user-images.githubusercontent.com/36922415/102613684-38fa5700-4133-11eb-9d79-4deae60fc43f.PNG)

redis-server must be redis-server.exe and you must add 2nd directory that would be directory to the config

**Comment by wallxq** [comment]
That works! Amazing :) thanks for very fast help!

**Comment by ham1255** [comment]
@Govindass should i cound this docs problem?

**Comment by Govindass** [comment]
> 
> 
> @Govindass should i cound this docs problem?

not sure, it's a redis usage issue, in linux the same problem happens too, that you must specify config directory (I don't know why it doesn't auto-specify if unspecified)
