### ISSUE TITLE
Add formatted message

### ISSUE THREAD

**Issue by wallxq** [Limework/RediSkript#12]
Proposes to add a formatted message. This is useful and needed if we want to send a message from a tooltip that has a placeholder or a variable in it. At this point "send redis message" works like "send" which causes problems with more advanced chat. It would be good for it to work like "send formatted".

**Comment by Govindass** [comment]
can't you "send formatted redis message" ?

**Comment by ham1255** [comment]
Oh he means send effect is conflicting with with send redis message effect?

**Comment by Govindass** [comment]
> Oh he means send effect is conflicting with with send redis message effect?

no no, there are no conflicts

**Comment by wallxq** [comment]
https://pastebin.com/qTS0XtGA <- skript
![lore](https://user-images.githubusercontent.com/36922415/103636600-860b6500-4f4a-11eb-99c4-902f30f7c2bd.png)
Lore shows on hover only 1 case with formatted.

**Comment by Govindass** [comment]
> 
> 
> https://pastebin.com/qTS0XtGA <- skript
> ![lore](https://user-images.githubusercontent.com/36922415/103636600-860b6500-4f4a-11eb-99c4-902f30f7c2bd.png)
> Lore shows on hover only 1 case with formatted.

this is not full code, can you show "on redis message" part?

**Comment by wallxq** [comment]
Ah okay my bad.. I have so many scripts that I forgot that redis message is triggered by "on redis message" and what we are going to do about it is our own will.
