### ISSUE TITLE
#question "MaxConnections"

### ISSUE THREAD

**Issue by wallxq** [Limework/RediSkript#13]
What changes the value of "MaxConnections: 2" more is better? How does this affect performance database or CPU/RAM consumption?

**Comment by ham1255** [comment]
Its jedis pool connections which might increases messages per second

**Comment by Govindass** [comment]
as ham1255 said above, when there's ping between the redis server and your minecraft server, higher connections count can help

however I haven't noticed much difference with higher max connections count myself, using 2 has been just fine for me

if you aren't having issues with messages being delivered too slowly... I guess it shouldn't matter for you

**Comment by ham1255** [comment]
I forgot to mention that it doesnt effect performance￼
