### ISSUE TITLE
Unexpected behavior when using ::* variables

### ISSUE THREAD

**Issue by Govindass** [Limework/RediSkript#15]
set variable "-test::*" in redis channel "global" to "%unix timestamp of now%"

1st try it will be <none> when you do send "%{-test::*}%"
then set variable again
it'll have data
then set variable again
it will be <none> again
set variable again
it'll have data again

very weird, but very reproduceable and consistent problem

**Comment by ham1255** [comment]
Its found out to be skript bug

**Comment by Govindass** [comment]
fixed
