### ISSUE TITLE
Making use of jedis get set expire mget 

### ISSUE THREAD

**Issue by ham1255** [Limework/RediSkript#6]

**Comment by Govindass** [comment]
what is this?

**Comment by ham1255** [comment]
Since jedis has same stuff like skript variables so we could store string data 
In redis since we can hash::uuid > some data
And expire isnfor when stored data key get removed in seconds and delete deletes ofc

**Comment by ham1255** [comment]
Currently thinking of

Get new jedis instance and store it in {jedis1}


Get string from redis using {jedis1} and the key is "hi" and store results on {results}

Broadcast "%{results}%"

Close jedis instance {jedis1} //not closing the jedis will cause pool being exhausted + memory leak so close it after you use it

**Comment by GovindasOM** [comment]
I am closing this ticket due to inactivity and no real need for it that I can see right now
